version: "2.1"

networks:
  app_network:

# use "docker-compose build" to rebuild an image in case of dependecy changes
services:
  osrm:
    extends:
      file: ./osrm/docker-compose.yml
      service: osrm-backend
    networks:
      - app_network

  be:
    build: ./be-django
    networks:
      - app_network
    ports:
      - "7000:7000"
    volumes:
      - ./be-django:/usr/src
      - /usr/src/project/db/
    environment:
      OSRM_HOST: http://osrm:5000
      DB_REL_PATH: db/db.sqlite3
    command: >
      bash -c "
      rm -f /usr/src/project/db/db.sqlite3
      && python3 project/manage.py migrate
      && python3 project/manage.py runserver
      "

  fe:
    build: ./fe/feapp
    networks:
      - app_network
    ports:
      - "4200:4200"
    volumes:
      - ./fe/feapp:/app
      - /app/node_modules
    command: ng serve --host 0.0.0.0

  sim:
    build: ./sim
    networks:
      - app_network
    ports:
      - "5001:5001"
    volumes:
      - ./sim:/usr/src
    environment:
      BE_URL: http://be:7000
      OSRM_HOST: http://osrm:5000
    command: python /usr/src/exec/run_web_proc_anim.py
