apiVersion: apps/v1
kind: Deployment
metadata:
  name: be
spec:
  selector:
    matchLabels:
      app: csa-vc
      tier: backend
  replicas: 2
  template:
    metadata:
      labels:
        app: csa-vc
        tier: backend
    spec:
      containers:
        - name: be-container
          image: csa_vc_be:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 7000
      initContainers:
        - name: wait-for-postgres
          image: busybox:1.28
          command:
            ["sh", "-c", "while ! nc -z postgres 5432; do sleep 2; done;"]
        - name: wait-for-osrm
          image: busybox:1.28
          command: ["sh", "-c", "while ! nc -z osrm 5000; do sleep 2; done;"]

---
apiVersion: v1
kind: Service
metadata:
  name: be
spec:
  type: NodePort
  ports:
    - port: 7000
  selector:
    app: csa-vc
    tier: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: osrm
spec:
  selector:
    matchLabels:
      app: csa-vc
      tier: osrm
  replicas: 1
  template:
    metadata:
      labels:
        app: csa-vc
        tier: osrm
    spec:
      containers:
        - name: osrm-container
          image: csa_vc_osrm:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: osrm
spec:
  type: NodePort
  ports:
    - port: 5000
  selector:
    app: csa-vc
    tier: osrm

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fe
spec:
  selector:
    matchLabels:
      app: csa-vc
      tier: frontend
  template:
    metadata:
      labels:
        app: csa-vc
        tier: frontend
    spec:
      containers:
        - name: fe-container
          image: csa_vc_fe:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: fe
spec:
  type: NodePort
  ports:
    - port: 80
  selector:
    app: csa-vc
    tier: frontend

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pg
spec:
  selector:
    matchLabels:
      app: csa-vc
      tier: db
  template:
    metadata:
      labels:
        app: csa-vc
        tier: db
    spec:
      containers:
        - name: pg-container
          image: postgres:9.6.20
          imagePullPolicy: Never
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    app: csa-vc
    tier: db
