# Generated by Django 3.0.5 on 2020-05-01 10:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('beapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tour',
            name='truck',
        ),
        migrations.AddField(
            model_name='truck',
            name='tour',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='beapp.Tour'),
        ),
    ]
